# Generated by Django 3.1.6 on 2021-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_n',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
