# Generated by Django 3.1.6 on 2021-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210220_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_n',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
